name: Setup Branch Protection

on:
  workflow_dispatch:  # 手动触发

jobs:
  setup-protection:
    runs-on: ubuntu-latest
    steps:
    - name: Setup branch protection
      uses: actions/github-script@v8
      with:
        script: |
          try {
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'markdown-lint',
                  'validate-structure'
                ]
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            });
            console.log('✅ Branch protection rules set successfully');
          } catch (error) {
            console.error('❌ Failed to set branch protection:', error.message);
          }